cache: bundler

jobs:
  include:
    - stage: lint
      language: node_js
      node_js:
        - "node"
      script: npm run eslint
    - stage: test
      language: node_js
      node_js:
        - "node"
      script:
        - "npm run test"
        - "npm run ci:sendCoverage"
    - stage: deploy
      #General Setup
      if: tag = true
      language: node_js
      node_js:
        - "node"
      #Create Changelog
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - nvm install node
          - npx semantic-release
      #Github Releases
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file: "CHANGELOG.md"
        skip_cleanup: true
      #NPM publish
      #Github Pages
